[tool.poetry]
name = "shushupe"
version = "0.1.0"
description = "Shushupe is a free and open source blogging platform."
homepage = "https://gahd.net/shushupe/"
authors = ["Gustavo Adolfo Huarcaya Delgado <diavolo@gahd.net>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2.5"
djangorestframework = "^3.14.0"
drf-spectacular = "^0.26.4"
mistune = "^3.0.1"
pygments = "^2.16.1"
python-dotenv = "^1.0.0"
gunicorn = "^21.2.0"
sentry-sdk = "^1.31.0"
psycopg = {extras = ["binary"], version = "^3.1.10"}
nanoid = "^2.0.0"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.4"
flake8 = "^6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
