[tool.poetry]
name = "shushupe"
version = "0.1.0"
description = "Shushupe is a free and open source blogging platform."
homepage = "https://gahd.net/shushupe/"
authors = ["Gustavo Adolfo Huarcaya Delgado <diavolo@gahd.net>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2.1"
djangorestframework = "^3.14.0"
psycopg2-binary = "^2.9.6"
drf-spectacular = "^0.26.2"
mistune = "^2.0.5"
mistune-contrib = "^0.1"
pygments = "^2.15.1"
python-dotenv = "^1.0.0"
gunicorn = "^20.1.0"
sentry-sdk = "^1.24.0"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.2"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
