# Generated by Django 5.2.15 on 2026-08-29 21:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_auto_20220404_2156'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=9)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('allow_comments', models.BooleanField(default=False)),
                ('protected_with_password', models.BooleanField()),
                ('post_password', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True, editable=False)),
                ('pub_type', models.CharField(choices=[('article', 'Article'), ('note', 'Note'), ('page', 'Page')], default='Consumption', editable=False, max_length=11)),
                ('consumption_type', models.CharField(choices=[('album', 'Album'), ('article', 'Article'), ('book', 'Book'), ('comic_manga', 'Comic/Manga'), ('course', 'Course'), ('game', 'Game'), ('movie', 'Movie'), ('paper', 'Paper'), ('playlist', 'Playlist'), ('podcast', 'Podcast'), ('series', 'Series'), ('single', 'Single'), ('track', 'Track'), ('tv_show', 'TV Show'), ('video', 'Video')], max_length=20)),
                ('format', models.CharField(blank=True, choices=[('apple_music', 'Apple Music'), ('apple_podcasts', 'Apple Podcasts'), ('audiobook', 'Audiobook'), ('bandcamp', 'Bandcamp'), ('blu_ray', 'Blu-ray'), ('book', 'Book'), ('broadcast', 'Broadcast'), ('cassette', 'Cassette'), ('cd', 'CD'), ('cinema', 'Cinema'), ('console', 'Console'), ('deezer', 'Deezer'), ('digital', 'Digital'), ('digital_download', 'Digital download'), ('digital_rental', 'Digital rental'), ('download', 'Download'), ('dvd', 'DVD'), ('ebook', 'Ebook'), ('handheld', 'Handheld'), ('hardcover', 'Hardcover'), ('hybrid', 'Hybrid'), ('in_person', 'In person'), ('mobile', 'Mobile'), ('newsletter', 'Newsletter'), ('online', 'Online'), ('paperback', 'Paperback'), ('pc', 'PC'), ('pdf', 'PDF'), ('preprint', 'Preprint'), ('print', 'Print'), ('radio', 'Radio'), ('rss', 'RSS'), ('spotify', 'Spotify'), ('stream', 'Stream'), ('streaming', 'Streaming'), ('tabletop', 'Tabletop'), ('tidal', 'Tidal'), ('trade_paperback', 'Trade paperback'), ('tv_broadcast', 'TV broadcast'), ('vimeo', 'Vimeo'), ('vinyl', 'Vinyl'), ('web', 'Web'), ('webtoon', 'Webtoon'), ('youtube', 'YouTube'), ('youtube_music', 'YouTube Music')], help_text='How or where the content is consumed (e.g. vinyl, streaming, cinema).', max_length=20)),
                ('consumption_status', models.CharField(choices=[('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('progress', models.CharField(blank=True, help_text='e.g. page 13/100, season 2/10, episode 3/10, etc.', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, help_text='16:9 aspect ratio image e.g. 640x360', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.media')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
            ],
            options={
                'ordering': ('-pub_date',),
                'abstract': False,
            },
        ),
    ]
