# Generated by Django 3.1 on 2020-08-23 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=9)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('allow_comments', models.BooleanField(default=False)),
                ('protected_with_password', models.BooleanField()),
                ('post_password', models.CharField(blank=True, max_length=500)),
                ('site_url', models.URLField(unique=True)),
                ('content', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True, editable=False)),
                ('pub_type', models.CharField(choices=[('article', 'Article'), ('note', 'Note'), ('page', 'Page')], default='Bookmark', max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='core.Tag')),
            ],
            options={
                'ordering': ('-pub_date',),
                'abstract': False,
            },
        ),
    ]
