# Generated by Django 3.1 on 2020-10-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_type',
            field=models.CharField(choices=[('article', 'Article'), ('note', 'Note'), ('page', 'Page')], default='Article', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='pub_type',
            field=models.CharField(choices=[('article', 'Article'), ('note', 'Note'), ('page', 'Page')], default='Bookmark', max_length=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_type',
            field=models.CharField(choices=[('article', 'Article'), ('note', 'Note'), ('page', 'Page')], default='Note', max_length=10),
        ),
        migrations.AlterField(
            model_name='page',
            name='pub_type',
            field=models.CharField(choices=[('article', 'Article'), ('note', 'Note'), ('page', 'Page')], default='Page', max_length=10),
        ),
    ]
