# Generated by Django 3.1 on 2020-10-06 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20201006_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('content_html', models.TextField(editable=False)),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=9)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('allow_comments', models.BooleanField(default=False)),
                ('protected_with_password', models.BooleanField()),
                ('post_password', models.CharField(blank=True, max_length=500)),
                ('pub_type', models.CharField(choices=[('article', 'Article'), ('note', 'Note'), ('page', 'Page')], default='Changelog', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='core.Tag')),
            ],
            options={
                'ordering': ('-pub_date',),
                'abstract': False,
            },
        ),
    ]
