# Generated by Django 3.2.6 on 2022-03-10 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210803_1340'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Changelog',
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Changelog'
                )
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Changelog',
                    table='changelog_changelog'
                )
            ]
        )
    ]
