# Generated by Django 3.2.6 on 2022-03-11 01:13

from unicodedata import name
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_changelog'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Bookmark',
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Bookmark',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Bookmark',
                    table='bookmark_bookmark'
                )
            ]
        )
    ]
