# Generated by Django 3.2.6 on 2022-03-22 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_bookmark'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Note',
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Note',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Note',
                    table='note_note'
                )
            ]
        )
    ]
