# Generated by Django 3.2.6 on 2022-04-05 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='name',
            new_name='title',
        ),
    ]
