# Generated by Django 3.2.6 on 2022-04-05 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='name',
            new_name='title',
        ),
    ]
