# Generated by Django 5.2.6 on 2026-03-23 00:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_auto_20220404_2156'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200)),
                ('review_topic_type', models.CharField(choices=[('artist', 'Artist'), ('author', 'Author'), ('brand', 'Brand'), ('chain', 'Chain'), ('collection', 'Collection'), ('creator', 'Creator'), ('franchise', 'Franchise'), ('general', 'General'), ('saga', 'Saga'), ('series', 'Series'), ('studio', 'Studio'), ('universe', 'Universe')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, help_text='1:1 aspect ratio image e.g. 320x320', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.media')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent topic for subtopics (e.g. a saga or franchise)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='review.reviewtopic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('content_html', models.TextField(editable=False)),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=9)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('allow_comments', models.BooleanField(default=False)),
                ('protected_with_password', models.BooleanField()),
                ('post_password', models.CharField(blank=True, max_length=500)),
                ('pub_type', models.CharField(default='Review', editable=False, max_length=10)),
                ('review_type', models.CharField(choices=[('anime', 'Anime'), ('books', 'Books'), ('comics/manga', 'Comics/Manga'), ('courses', 'Courses'), ('events', 'Events'), ('games', 'Games'), ('hotels', 'Hotels'), ('movies', 'Movies'), ('music', 'Music'), ('other', 'Other'), ('podcasts', 'Podcasts'), ('products', 'Products'), ('restaurants', 'Restaurants'), ('series', 'Series'), ('services', 'Services'), ('software', 'Software'), ('tv shows', 'TV Shows')], max_length=12)),
                ('rating', models.DecimalField(choices=[(Decimal('1.0'), '1.0 - Pésimo'), (Decimal('1.5'), '1.5 - Muy deficiente'), (Decimal('2.0'), '2.0 - Deficiente'), (Decimal('2.5'), '2.5 - Por debajo del promedio'), (Decimal('3.0'), '3.0 - Promedio'), (Decimal('3.5'), '3.5 - Ligeramente superior al promedio'), (Decimal('4.0'), '4.0 - Bueno'), (Decimal('4.5'), '4.5 - Muy bueno'), (Decimal('5.0'), '5.0 - Excelente')], decimal_places=1, max_digits=3)),
                ('volume', models.IntegerField(blank=True, help_text='Season, volume, or installment number', null=True)),
                ('item_number', models.IntegerField(blank=True, help_text='Episode, track, issue, or chapter number', null=True)),
                ('item_release_date', models.DateField(blank=True, null=True)),
                ('item_url', models.URLField(blank=True, max_length=255, null=True)),
                ('pros', models.TextField(blank=True)),
                ('cons', models.TextField(blank=True)),
                ('is_recommended', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, choices=[('ARS', 'ARS - Argentine Peso'), ('AUD', 'AUD - Australian Dollar'), ('BRL', 'BRL - Brazilian Real'), ('CAD', 'CAD - Canadian Dollar'), ('CLP', 'CLP - Chilean Peso'), ('CNY', 'CNY - Chinese Yuan'), ('COP', 'COP - Colombian Peso'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('JPY', 'JPY - Japanese Yen'), ('MXN', 'MXN - Mexican Peso'), ('PEN', 'PEN - Peruvian Sol'), ('USD', 'USD - US Dollar')], help_text='Currency for the listed price', max_length=3)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item_image', models.ForeignKey(blank=True, help_text='1:1 aspect ratio image e.g. 320x320', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.media')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
                ('review_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='review.reviewtopic')),
            ],
            options={
                'ordering': ('-pub_date',),
                'abstract': False,
            },
        ),
    ]
